apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  namespace: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: risilze/cicd_project:54b48447c0ed69fdc4eb7fc0743848d48b6d9147
          ports:
            - containerPort: 8080
