apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample_webapp
  name: cicd_service
  namespace: cicd
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
  selector:
    app: sample_webapp